version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: lindani06-flask_live_app:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/todo
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}